pipeline {
    agent any

    stages {
        stage('Cleanup'){
            steps {
                cleanWs()
            }
            
        }
        stage('Git') {
            steps {
                git credentialsId: 'github-jenkins', url: 'git@github.com:brsockel/iac.git'
            }
        }
        stage('terraform'){
            steps {
                sh ('terraform -chdir="Jenkins/Terraform-HelloWorld" init -no-color')
                sh ('terraform -chdir="Jenkins/Terraform-HelloWorld" apply -auto-approve -no-color' )
            }
        }
    }
}
